name: Blackwhitemedia
favicon: null
layout_spectrum: 0.8644445016980171
typography_spectrum: 0.9791713079903275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.36763203772716224
  lightness: 0.976100520696491
  saturation: 0.18552308971993625
  rhythmicContrast: 0.21256137965247035
purpose: []
